### PR TITLE
Fix spelling

### PR DESCRIPTION
**Pull request by iczero**
It's "Android" not "Anroid"

### CODE REVIEW

**Comment by jacob1** [comment]
Merged. I noticed this yesterday, I was going to fix it for version 1.1 (or 1.0.1, however I decide to do version numbers). I guess now I don't have to :P. Although might still make my own extra modifications later.

**Comment by iczero** [comment]
OK. Could you also please change the readme to show how to compile the Android app? That would probably be helpful.

**Comment by jacob1** [comment]
Yes. But first I need to figure out how _I_ compiled it before I can help other people do it :P

I wrote down everything I downloaded and changed so probably should be able to figure it out, if you want to come back on IRC I could help you (I think you need linux but not sure).

**Comment by iczero** [comment]
OK.

**Pull request merged**
